name: dotslashstream

networks:
  stream_external:
    driver: bridge
    internal: false
  stream_internal:
    driver: bridge
    internal: true

services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 80:3000
    networks:
      - stream_external
    volumes:
      - stream_logs:/var/log/stream
    depends_on:
      backend:
        condition: service_healthy
      postgres:
        condition: service_healthy

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - 9340:9340
    networks:
      - stream_internal
      - stream_external
    volumes:
      - stream_logs:/var/log/stream
      - ./scripts/backend:/app/scripts
    env_file:
      - ./.envs/backend.env
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9340/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - stream_internal
    volumes:
      - stream_databases:/var/lib/postgresql/data
    env_file:
      - ./.envs/postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  stream_logs:
  stream_databases:
